apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: self
  name: self
spec:
  replicas: 3
  selector:
    matchLabels:
      run: self
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: self
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_NAMESPACE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KUBERNETES_NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: runlevl4/selfdemo:1.0
        imagePullPolicy: Always
        name: self
        resources:
          requests:
            cpu: 25m
            memory: 50M
          limits:
            cpu: 100m
            memory: 100M
        livenessProbe:
          httpGet:
            path: /info
            port: 8000
          initialDelaySeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
